# Generated by Django 4.0.5 on 2023-10-28 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='Sin número', help_text='Ingresa número', max_length=20, verbose_name='Número de teléfono')),
                ('user_type', models.CharField(choices=[('1', 'Administrador'), ('2', 'Cliente')], default='2', help_text='Seleccione un tipo de usuario', max_length=255, verbose_name='Tipo de usuario')),
                ('user', models.OneToOneField(help_text='Seleccione Usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Información adicional',
                'verbose_name_plural': 'Informaciones adicionales',
            },
        ),
    ]
