# Generated by Django 4.0.5 on 2023-10-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformationmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='userinformationmodel',
            name='identification',
            field=models.CharField(blank=True, max_length=15, verbose_name='Documento de identidad'),
        ),
    ]
