# Generated by Django 4.0.5 on 2023-10-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userinformationmodel_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformationmodel',
            name='address',
            field=models.CharField(blank='', max_length=255, null=True),
        ),
    ]
