# Generated by Django 4.0.5 on 2023-10-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinformationmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationmodel',
            name='identification',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Documento de identidad'),
        ),
    ]
