# Generated by Django 4.0.5 on 2023-10-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='estado_producto',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='url_img',
            new_name='image',
        ),
    ]
