# Generated by Django 4.0.5 on 2023-10-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pedido_productopedido_historial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productopedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='productopedido',
            name='producto',
            field=models.ManyToManyField(to='core.producto', verbose_name='Productos'),
        ),
    ]
