# Generated by Django 4.0.5 on 2023-10-29 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_productopedido_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productopedido',
            name='producto',
        ),
        migrations.AddField(
            model_name='productopedido',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto', verbose_name='Productos'),
        ),
    ]
