# Generated by Django 4.0.5 on 2023-10-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_productopedido_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopedido',
            name='precio',
            field=models.DecimalField(decimal_places=5, max_digits=25, verbose_name='Precio'),
        ),
    ]
