# Generated by Django 4.0.5 on 2023-10-30 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_productopedido_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pedido', verbose_name='Pedido'),
        ),
    ]
