# Generated by Django 4.0.5 on 2023-10-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pedido_precio_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precio_Total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=5, max_digits=25, null=True, verbose_name='Precio total'),
        ),
    ]
