# Generated by Django 4.0.5 on 2023-11-04 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_producto_coleccion_alter_nosotros_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='coleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.coleccion', verbose_name='Coleccion'),
        ),
    ]
