# Generated by Django 4.0.5 on 2023-11-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_nosotros_image'),
        ('core', '0022_alter_producto_coleccion'),
    ]

    operations = [
    ]
