# Generated by Django 4.0.5 on 2023-11-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_producto_coleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='titulo',
            field=models.CharField(max_length=250, null=True, verbose_name='Titulo'),
        ),
    ]
