# Generated by Django 4.0.5 on 2023-11-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_nosotros_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='descripcion',
            field=models.CharField(max_length=250, null=True, verbose_name='Descripción'),
        ),
    ]
