# Generated by Django 4.0.5 on 2023-11-05 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_alter_nosotros_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuponUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cupon')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'cupon')},
            },
        ),
    ]
