# Generated by Django 4.0.5 on 2023-11-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_producto_coleccion'),
        ('core', '0025_alter_nosotros_descripcion'),
    ]

    operations = [
    ]
