# Generated by Django 4.0.5 on 2023-11-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20231104_2022'),
        ('core', '0027_producto_descuento'),
    ]

    operations = [
    ]
