# Generated by Django 4.0.5 on 2023-11-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20231105_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
    ]
