# Generated by Django 4.0.5 on 2023-11-07 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='empresa_envio',
            field=models.CharField(default='Asignar empresa', max_length=50, null=True, verbose_name='Empresa de envio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_guia',
            field=models.CharField(default='Asignar número de guia', max_length=50, null=True, verbose_name='Número de guia'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20, verbose_name='Estado de producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Id pedido'),
        ),
    ]
