# Generated by Django 4.0.5 on 2023-11-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_pedido_empresa_envio_pedido_numero_guia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(blank=True, default='Pendiente', max_length=50, null=True, verbose_name='Estado de producto'),
        ),
    ]
