# Generated by Django 4.0.5 on 2023-11-11 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0031_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuponutilizado',
            name='pedido',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='cuponutilizado',
            name='cupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cupon', verbose_name='Cupon'),
        ),
        migrations.AlterField(
            model_name='cuponutilizado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50, verbose_name='Estado del pedido'),
        ),
    ]
