# Generated by Django 4.0.5 on 2023-11-11 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_cuponutilizado_pedido_alter_cuponutilizado_cupon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuponutilizado',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cuponutilizado',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='cuponutilizado',
            unique_together={('usuario', 'cupon', 'pedido')},
        ),
    ]
