# Generated by Django 4.0.5 on 2023-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_cuponutilizado_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='empresa_envio',
            field=models.CharField(default='Sin asignar', max_length=50, null=True, verbose_name='Empresa de envio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_guia',
            field=models.CharField(default='Sin asignar', max_length=50, null=True, verbose_name='Número de guia'),
        ),
    ]
