# Generated by Django 4.0.5 on 2023-11-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_pedido_empresa_envio_alter_pedido_numero_guia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='descripcion',
            field=models.CharField(max_length=5000, null=True, verbose_name='Descripción'),
        ),
    ]
