# Generated by Django 4.0.5 on 2023-11-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_nosotros_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icon',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Icono'),
        ),
    ]
