# Generated by Django 4.0.5 on 2023-11-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_categoria_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Cancelado', 'Cancelado'), ('Devolución', 'Devolucion')], default='Pendiente', max_length=50, verbose_name='Estado del pedido'),
        ),
    ]
